version: '3.4'

services:
  mvpfullstackproject:
    image: mvpfullstackproject
    build:
      context: backend 
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
